spring:
  profiles:
    active: dev

  application:
    name: SportAdministrationSystem

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:postgresql://localhost:5432/sport_admin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  docker:
    compose:
      enabled: true

server:
  port: 8081

app:
  cors:
    allowed-origins:
      - http://localhost:5175

jwt:
  # DEV-секрет (достатньо довгий для HS256)
  secret: Qb2P8d9eS3nZk7cA1rT5uV8xY2mN4pL6wH0J3K9R2F5M8C1D7E4G6H8J0L2Q4S6
  # назви, які очікує код
  access-exp-min: 60
  refresh-exp-days: 7
  # на випадок, якщо десь у коді інші ключі — лишаю дублікати (не завадять)
  access-ttl-minutes: 60
  refresh-ttl-days: 7

telegram:
  bot:
    token: 8470789325:AAFEfsjKlPbOkBWPVXfN99o9ahumV9_vWHg
    username: EventKPIbot
    # додав обидва варіанти ключа, щоб точно співпало з биндингом
    chat-id: -4894126161
    defaultChatId: -4894126161

dispatcher:
  batch-size: 50
  retry-batch-size: 200
  max-attempts: 5
  interval-ms: 60000

logging:
  level:
    org.springframework.security: INFO
    com.example.sportadministrationsystem: INFO
