server:
  port: 8081

spring:
  application:
    name: SportAdministrationSystem
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sport_admin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  docker:
    compose:
      enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:5175

jwt:
  secret: "Y0urSup3r$3cretJWTK3yWith32+CharsMin"
  access-exp-min: 60
  refresh-exp-days: 14

logging:
  level:
    org.springframework.security: INFO
