server:
  port: 8081

spring:
  application:
    name: SportAdministrationSystem
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# додай свої datasource/liquibase тут за потреби

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:5175

jwt:
  # Мінімум 256-біт. Замінити на власний секрет.
  secret: "change-this-256-bit-secret-change-this-256-bit-secret-"
  access-exp-min: 60
  refresh-exp-days: 14

logging:
  level:
    org.springframework.security: INFO
